name: "Data storage test"

on:
  workflow_dispatch

jobs:
  save-data:
    runs-on: ubuntu-latest
    steps:
      - name: Write Test Data
        run: |
          mkdir -p ${{ github.workspace }}/test 
          touch ${{ github.workspace }}/test/data
          echo "${{ github.ref_name }}" > ${{ github.workspace }}/test/data
          echo "test data" >> ${{ github.workspace }}/test/data
      - name: Save Data
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}/test
          key: testData.${{ github.ref_name }}