name: "Data storage test"

on:
  workflow_dispatch

jobs:
  save-data:
    runs-on: ubuntu-latest
    steps:
      - name: Write Test Data
        run: |
          mkdir -p /test 
          touch /test/data
          echo "test data" >> /test/data
      - name: Save Data
        uses: actions/cache/save@v4
        with:
          path: /test
          key: testData.${{ github.ref_name }}