name: "Data storage test"

on:
  workflow_dispatch
permissions:
  contents: read
  # require to delete cache
  # https://docs.github.com/en/rest/actions/cache?apiVersion=2022-11-28#delete-github-actions-caches-for-a-repository-using-a-cache-key
  actions: write

jobs:
  save-data:
    runs-on: ubuntu-latest
    steps:
      - name: Load Data
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/test2
          key: testData.branch
      - name: Display Test Data
        run: |
          cat ${{ github.workspace }}/test/data
      - name: Write Test Data
        if: always()
        run: |
          mkdir -p ${{ github.workspace }}/test 
          touch ${{ github.workspace }}/test/data
          echo "${{ github.ref_name }}" > ${{ github.workspace }}/test/data
          echo "test data" >> ${{ github.workspace }}/test/data
      - name: Clean Cache
        if: always()
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "testData.branch" --confirm -R ${{ github.repository }}
      - name: Save Data
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}/test
          key: testData.branch