name: "Data retrieval test"

on:
  workflow_dispatch

jobs:
  retrieve-data:
    runs-on: ubuntu-latest
    steps:
      - name: Load Data
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/test
          key: testData.main
      - name: Write Test Data
        run: |
          cat ${{ github.workspace }}/test/data